### PR TITLE
Relative Positional Embedding (fixed or learnable)

### PR DESCRIPTION
**Pull request by freewym**

### CODE REVIEW

**Comment by sw005320** [comment]
@freewym, did you observe some improvements?
I’m curious.

**Comment by freewym** [comment]
@sw005320 I am still running the experiments on non-streaming models. The main purpose for this is for streaming models though.

May I ask whether you found relative embeddings helpful in non-streaming models?

**Comment by sw005320** [comment]
The conclusion is mixed, but there are some solid benefits for the long recording.

**Comment by freewym** [comment]
@sw005320 FYI, my experiments on Librispeech show that: for encoders using relative embeddings is better than absolute ones, and relative sinusoidal is better than relative learned; for decoders, however, absolute sinusoidal is the best.

**Pull request merged**
